version: '3'
services:
  nginx:
    image: ${NGINX_IMAGE}
    container_name: ${NGINX_CONTAINER}
    depends_on:
      - fastapi
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ${NGINX_CONF}:/etc/nginx/nginx.conf
      - ${NGINX_CONF_DIR}:/etc/nginx/conf.d
      - ${NGINX_LOGS}:/var/log/nginx
      - ${NGINX_HTML}:/usr/share/nginx/html
    networks:
      backend-network:
        ipv4_address: ${NGINX_IP}

  fastapi:
    image: ${FASTAPI_IMAGE}
    build:
      context: .
      dockerfile : ${FASTAPI_DOCKERFILE}
    restart: on-failure
    container_name: ${FASTAPI_CONTAINER}
    volumes:
      - ${APP_DIR}:/app/was/app
      - ${REQUIREMENTS}:/app/was/requirements.txt
    entrypoint: ["uvicorn"]
    command:
      - "app.main:app"
      - "--reload"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "10004"
    networks:
      backend-network:
        ipv4_address: ${FASTAPI_IP}

networks:
  backend-network:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}
          gateway: ${NETWORK_GATEWAY}
