version: '3'
services:
  nginx:
    image: ${NGINX_IMAGE}
    container_name: ${NGINX_CONTAINER}
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ${NGINX_CONF}:/etc/nginx/nginx.conf
      - ${NGINX_CONF_DIR}:/etc/nginx/conf.d
      - ${NGINX_LOGS}:/var/log/nginx
      - ${NGINX_HTML}:/usr/share/nginx/html
